# Generated by Django 5.1.6 on 2025-03-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_message_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
    ]
